import { describe, expect, it } from 'vitest';
import { EMPTY_FACILITY_POINTS, buildFacilityPoints } from './facilityPoints';
import type { Facility, FacilityMetric } from '../types';

// Inline fixtures only — src/generated/* and public/facilities/* are
// generated by `npm run sync-data`, which does NOT run before `npm run test`
// (see CLAUDE.md 「可視化実装で判明した罠」8 and facilityShard.test.ts's note).

// Mirrors the real METRICS order closely enough for this test's purposes:
// what matters is that 'beds_total' is present at a non-zero index, so a
// naive index-0 assumption would be caught.
const METRICS: Array<Pick<FacilityMetric, 'key'>> = [
  { key: 'beds_high_acute' },
  { key: 'beds_total' },
  { key: 'beds_acute' },
];

function makeFacility(overrides: Partial<Facility> = {}): Facility {
  return {
    record_id: 'R7-0101-14',
    facility_name: '市立函館病院',
    municipality: '函館市',
    values: [292, 582, 270],
    value_status: ['observed', 'observed', 'observed'],
    functions: ['地域支援'],
    match_status: 'matched',
    coordinates: [140.7301711, 41.80541985],
    ...overrides,
  };
}

describe('buildFacilityPoints', () => {
  it('excludes facilities without coordinates', () => {
    const withCoords = makeFacility();
    const withoutCoords = makeFacility({
      record_id: 'R7-0101-99',
      match_status: 'unmatched',
      coordinates: undefined,
    });

    const result = buildFacilityPoints([withCoords, withoutCoords], METRICS);

    expect(result.features).toHaveLength(1);
    expect(result.features[0].properties.record_id).toBe('R7-0101-14');
  });

  it('excludes candidate_only facilities (no coordinates, per doc/REQUIREMENTS.md §4.3)', () => {
    const candidateOnly = makeFacility({
      record_id: 'R7-0101-50',
      match_status: 'candidate_only',
      coordinates: undefined,
    });

    const result = buildFacilityPoints([candidateOnly], METRICS);

    expect(result).toEqual(EMPTY_FACILITY_POINTS);
  });

  it('produces flat scalar properties only (no arrays/objects)', () => {
    const result = buildFacilityPoints([makeFacility()], METRICS);
    const props = result.features[0].properties;

    for (const value of Object.values(props)) {
      expect(typeof value === 'string' || typeof value === 'number').toBe(true);
    }
  });

  it('sets geometry to a Point using the facility coordinates verbatim (lon, lat)', () => {
    const result = buildFacilityPoints([makeFacility()], METRICS);
    expect(result.features[0].geometry).toEqual({
      type: 'Point',
      coordinates: [140.7301711, 41.80541985],
    });
  });

  it('includes beds_total when the metric is observed', () => {
    const result = buildFacilityPoints([makeFacility()], METRICS);
    expect(result.features[0].properties.beds_total).toBe(582);
  });

  it('omits beds_total (not 0) when the metric is not observed', () => {
    const facility = makeFacility({
      values: [292, null, 270],
      value_status: ['observed', 'source_dash', 'observed'],
    });
    const result = buildFacilityPoints([facility], METRICS);

    expect('beds_total' in result.features[0].properties).toBe(false);
  });

  it('omits beds_total when the value_status array marks it observed but the value is null (defensive)', () => {
    const facility = makeFacility({
      values: [292, null, 270],
      value_status: ['observed', 'observed', 'observed'],
    });
    const result = buildFacilityPoints([facility], METRICS);

    expect('beds_total' in result.features[0].properties).toBe(false);
  });

  it('omits beds_total entirely when metrics has no beds_total key (defensive)', () => {
    const result = buildFacilityPoints([makeFacility()], [{ key: 'beds_acute' }]);
    expect('beds_total' in result.features[0].properties).toBe(false);
  });

  it('returns an empty FeatureCollection for an empty facilities array', () => {
    expect(buildFacilityPoints([], METRICS)).toEqual(EMPTY_FACILITY_POINTS);
  });

  it('returns an empty FeatureCollection for null/undefined facilities without throwing', () => {
    expect(buildFacilityPoints(null, METRICS)).toEqual(EMPTY_FACILITY_POINTS);
    expect(buildFacilityPoints(undefined, METRICS)).toEqual(EMPTY_FACILITY_POINTS);
  });

  it('returns an empty FeatureCollection when no facility has coordinates', () => {
    const a = makeFacility({ record_id: 'a', match_status: 'unmatched', coordinates: undefined });
    const b = makeFacility({ record_id: 'b', match_status: 'candidate_only', coordinates: undefined });
    expect(buildFacilityPoints([a, b], METRICS)).toEqual(EMPTY_FACILITY_POINTS);
  });

  it('does not carry the functions array or any other nested field into properties', () => {
    const result = buildFacilityPoints([makeFacility()], METRICS);
    const props = result.features[0].properties as unknown as Record<string, unknown>;
    expect('functions' in props).toBe(false);
    expect('values' in props).toBe(false);
    expect('value_status' in props).toBe(false);
    expect('coordinates' in props).toBe(false);
    expect('match_status' in props).toBe(false);
  });
});
