import { describe, expect, it } from 'vitest';
import { buildAreaShard, buildFacilitySummary, shardFileName } from '../../scripts/lib/facilities.mjs';

// Inline fixtures only — web/src/generated/* and web/public/facilities/* are
// generated by `npm run sync-data`, which does NOT run before `npm run test`
// (vitest has no pre* hook; see CLAUDE.md "可視化実装で判明した罠" #8). Do
// not import generated output from this file.

function makeFacility(overrides: Partial<Record<string, unknown>> = {}) {
  return {
    record_id: 'R7-0101-14',
    facility_name: '市立函館病院',
    municipality: '函館市',
    values: [582, 292, 270, 0, 0, 20, 130, 0.2, 22.37, 6572, 1983, 155, 5819, 12.15, 11.27, null, null, 9184, 6489, null, null],
    value_status: [
      'observed', 'observed', 'observed', 'observed', 'observed', 'observed', 'observed',
      'observed', 'observed', 'observed', 'observed', 'observed', 'observed', 'observed',
      'observed', 'source_dash', 'source_dash', 'observed', 'observed', 'source_dash', 'source_dash',
    ],
    functions: ['地域支援', '三次救急', '二次救急'],
    match_status: 'matched',
    coordinates: [140.7301711, 41.80541985],
    ...overrides,
  };
}

function makeArea(area_code: string, overrides: Partial<Record<string, unknown>> = {}) {
  return {
    area_code,
    area_name: `Area ${area_code}`,
    pref_code: area_code.slice(0, 2),
    pref_name: 'Pref',
    facility_count: 1,
    geocoded_count: 1,
    facilities: [makeFacility()],
    ...overrides,
  };
}

function makeFacilitiesData(areas: Array<Record<string, unknown>>) {
  return {
    metadata: { title: 'test', source: {}, geo_linkage_source: {}, processing: {}, fields: {}, known_issues: [] },
    metrics: [{ key: 'beds_total', metric: '病床数', bed_function: '休棟中等含む計', label: '病床数（休棟中等含む計）' }],
    value_status_labels: { observed: '実測値' },
    areas,
  };
}

describe('buildAreaShard', () => {
  it('passes through all source-of-truth fields verbatim, including facilities', () => {
    const area = makeArea('0101');
    const shard = buildAreaShard(area);

    expect(shard).toEqual({
      area_code: '0101',
      area_name: 'Area 0101',
      pref_code: '01',
      pref_name: 'Pref',
      facility_count: 1,
      geocoded_count: 1,
      facilities: area.facilities,
    });
    // Same object reference (not re-parsed/re-sliced), per the brief:
    // "文字列としての切り出し（バイトスライス）は絶対にしないこと".
    expect(shard.facilities).toBe(area.facilities);
  });

  it('does not drop the facilities array', () => {
    const area = makeArea('0101', { facilities: [makeFacility(), makeFacility({ record_id: 'R7-0101-15' })] });
    const shard = buildAreaShard(area);
    expect(shard.facilities).toHaveLength(2);
  });
});

describe('buildFacilitySummary', () => {
  it('excludes the facilities array from each area entry', () => {
    const data = makeFacilitiesData([makeArea('0101'), makeArea('0102')]);
    const summary = buildFacilitySummary(data);

    for (const area of summary.areas) {
      expect('facilities' in area).toBe(false);
    }
  });

  it('keeps only area_code/facility_count/geocoded_count per area', () => {
    const data = makeFacilitiesData([makeArea('0101', { facility_count: 5, geocoded_count: 3 })]);
    const summary = buildFacilitySummary(data);

    expect(summary.areas).toEqual([{ area_code: '0101', facility_count: 5, geocoded_count: 3 }]);
  });

  it('preserves metadata, metrics and value_status_labels', () => {
    const data = makeFacilitiesData([makeArea('0101')]);
    const summary = buildFacilitySummary(data);

    expect(summary.metadata).toBe(data.metadata);
    expect(summary.metrics).toBe(data.metrics);
    expect(summary.value_status_labels).toBe(data.value_status_labels);
  });
});

describe('shardFileName', () => {
  it('returns "<area_code>.json" for a valid 4-digit code', () => {
    expect(shardFileName('0101')).toBe('0101.json');
    expect(shardFileName('2412')).toBe('2412.json');
  });

  it('throws for codes that are not exactly 4 digits', () => {
    expect(() => shardFileName('12')).toThrow();
    expect(() => shardFileName('abcd')).toThrow();
    expect(() => shardFileName('0101 ')).toThrow();
    expect(() => shardFileName('../x')).toThrow();
    expect(() => shardFileName('01011')).toThrow();
    expect(() => shardFileName('')).toThrow();
  });
});

describe('buildAreaShard / buildFacilitySummary handle missing-field patterns', () => {
  it('handles a facility without functions', () => {
    const facility = makeFacility();
    delete (facility as Partial<typeof facility>).functions;
    const area = makeArea('0101', { facilities: [facility] });

    const shard = buildAreaShard(area);
    expect('functions' in shard.facilities[0]).toBe(false);
  });

  it('handles a facility without coordinates (unmatched/candidate_only)', () => {
    const facility = makeFacility({ match_status: 'unmatched' });
    delete (facility as Partial<typeof facility>).coordinates;
    const area = makeArea('0101', { facilities: [facility], geocoded_count: 0 });

    const shard = buildAreaShard(area);
    expect('coordinates' in shard.facilities[0]).toBe(false);
    expect(shard.geocoded_count).toBe(0);
  });

  it('handles values with nulls mixed in (non-observed metrics)', () => {
    const facility = makeFacility({
      values: [null, 10, null],
      value_status: ['not_disclosed', 'observed', 'blank'],
    });
    const area = makeArea('0101', { facilities: [facility] });

    const shard = buildAreaShard(area);
    expect(shard.facilities[0].values).toEqual([null, 10, null]);
  });
});
