// Fetching/caching of per-area facility shards (web/public/facilities/<area_code>.json).
// Splits cleanly into:
//   - pure/side-effect-light helpers (facilityShardUrl, fetchFacilityShard,
//     createFacilityShardLoader) that vitest can exercise directly with a
//     mocked fetch — no DOM/React rendering required (this repo's vitest has
//     no jsdom/testing-library dependency, see facilityShard.test.ts)
//   - the React hook (useFacilityShard) that is a thin wrapper around the
//     loader, wiring it to useState/useEffect
//
// See CLAUDE.md "可視化実装で判明した罠" 8: web/src/generated/* and
// web/public/facilities/* are generated by `npm run sync-data`, which does
// NOT run before `npm run test` — this file and its test must not import them.

import { useCallback, useEffect, useRef, useState } from 'react';
import type { FacilityShard } from '../types';

/**
 * URL of an area's facility shard. Must be built from import.meta.env.BASE_URL
 * (vite.config.ts sets `base: './'`) rather than an absolute `/facilities/...`
 * path — an absolute path 404s once the site is deployed under a GitHub Pages
 * sub-path (`/<repo>/`).
 */
export function facilityShardUrl(areaCode: string): string {
  return `${import.meta.env.BASE_URL}facilities/${areaCode}.json`;
}

export interface FetchFacilityShardOptions {
  signal?: AbortSignal;
}

/**
 * Fetches and validates a single area's facility shard. Throws (rather than
 * returning a Result type) on a non-2xx response or an area_code mismatch
 * between the request and the response — the mismatch check catches a
 * misconfigured/stale shard file silently describing the wrong area.
 */
export async function fetchFacilityShard(
  areaCode: string,
  options: FetchFacilityShardOptions = {}
): Promise<FacilityShard> {
  const res = await fetch(facilityShardUrl(areaCode), { signal: options.signal });
  if (!res.ok) {
    throw new Error(`医療機関データの取得に失敗しました（区域コード ${areaCode}）: HTTP ${res.status}`);
  }
  const data = (await res.json()) as FacilityShard;
  if (data.area_code !== areaCode) {
    throw new Error(
      `医療機関データの区域コードが要求と一致しません（要求 ${areaCode} / 応答 ${data.area_code}）`
    );
  }
  return data;
}

export type FacilityShardStatus = 'idle' | 'loading' | 'loaded' | 'error';

export interface FacilityShardState {
  status: FacilityShardStatus;
  shard: FacilityShard | null;
  error: string | null;
}

const IDLE_STATE: FacilityShardState = { status: 'idle', shard: null, error: null };

// モジュールスコープのメモリキャッシュ。一度取得した区域は再選択時に再取得
// しない。失敗した取得は保存しない（retry()が毎回ネットワークへ再取得しに行く
// ことを保証するため）。
const shardCache = new Map<string, FacilityShard>();

export interface FacilityShardLoaderOptions {
  /** テスト用の差し替え。省略時はモジュールスコープの shardCache を使う。 */
  cache?: Map<string, FacilityShard>;
  /** テスト用の差し替え。省略時は fetchFacilityShard（実ネットワーク）を使う。 */
  fetcher?: (areaCode: string, options: FetchFacilityShardOptions) => Promise<FacilityShard>;
  onChange: (state: FacilityShardState) => void;
}

export interface FacilityShardLoaderHandle {
  /** 区域を選択する（nullで選択解除）。前回の取得が進行中なら中断する。 */
  request: (areaCode: string | null) => void;
  /** 現在選択中の区域について、キャッシュを使わず再取得する。 */
  retry: () => void;
  /** 進行中の取得を中断する（アンマウント時に呼ぶ）。 */
  dispose: () => void;
}

/**
 * useFacilityShard の非同期オーケストレーション本体。React の useState/
 * useEffect から切り離した状態機械にしているのは、「区域を素早く切り替えた
 * とき、古い区域のレスポンスが後から届いても新しい区域の表示を上書きしない」
 * という競合状態対策を、Reactのレンダリングに依存せず純粋なロジックとして
 * テストできるようにするため（vitestにDOM環境が無くフックを直接レンダーして
 * テストできないため。CLAUDE.md「可視化実装で判明した罠」8と同種の制約）。
 *
 * AbortControllerによるキャンセルだけでは不十分な点に注意: (a) キャッシュ
 * ヒット時はそもそもfetchが起きない、(b) abort()を呼んだ時点で既にネットワーク
 * 取得そのものは完了していた場合、signal.abortedは真になるがそれより前に
 * .thenが解決してしまう競合がありうる。そのため「今リクエストしているareaCode
 * と、応答が来た時点で現在選択されているareaCodeが一致するか」を
 * currentAreaCode変数で毎回確認してから状態を反映する。
 */
export function createFacilityShardLoader(options: FacilityShardLoaderOptions): FacilityShardLoaderHandle {
  const cache = options.cache ?? shardCache;
  const fetcher = options.fetcher ?? fetchFacilityShard;
  let currentAreaCode: string | null = null;
  let currentController: AbortController | null = null;

  function request(areaCode: string | null): void {
    currentController?.abort();
    currentController = null;
    currentAreaCode = areaCode;

    if (areaCode === null) {
      options.onChange(IDLE_STATE);
      return;
    }

    const cached = cache.get(areaCode);
    if (cached) {
      options.onChange({ status: 'loaded', shard: cached, error: null });
      return;
    }

    const controller = new AbortController();
    currentController = controller;
    options.onChange({ status: 'loading', shard: null, error: null });

    fetcher(areaCode, { signal: controller.signal })
      .then((shard) => {
        if (currentAreaCode !== areaCode) return; // superseded by a later selection
        cache.set(areaCode, shard);
        options.onChange({ status: 'loaded', shard, error: null });
      })
      .catch((err: unknown) => {
        if (currentAreaCode !== areaCode) return; // superseded
        if (controller.signal.aborted) return; // intentional cancellation, not a real error
        options.onChange({
          status: 'error',
          shard: null,
          error: err instanceof Error ? err.message : String(err),
        });
      });
  }

  function retry(): void {
    if (currentAreaCode === null) return;
    // The cache never holds a failed attempt (only successes are cached
    // above), so re-requesting the same area always re-issues the fetch.
    request(currentAreaCode);
  }

  function dispose(): void {
    currentController?.abort();
  }

  return { request, retry, dispose };
}

export interface UseFacilityShardResult {
  status: FacilityShardStatus;
  shard: FacilityShard | null;
  error: string | null;
  retry: () => void;
}

/**
 * 選択中の区域(areaCode)に対応する医療機関shardを取得するフック。
 * - areaCode===null のときは status: 'idle'
 * - 一度取得した区域はモジュールスコープのキャッシュから即座に返す（再取得しない）
 * - 区域を素早く切り替えても、古い区域のレスポンスが新しい区域の表示を上書きしない
 *   （createFacilityShardLoader参照）
 * - React 18 StrictModeの二重実行でも壊れない: loaderRefは同一コンポーネント
 *   インスタンス内で1つだけ生成され、クリーンアップでdispose()（=進行中の取得を
 *   中断）してから次のeffectが新しいrequest()を呼ぶ
 */
export function useFacilityShard(areaCode: string | null): UseFacilityShardResult {
  const [state, setState] = useState<FacilityShardState>(() => {
    if (areaCode !== null) {
      const cached = shardCache.get(areaCode);
      if (cached) return { status: 'loaded', shard: cached, error: null };
    }
    return areaCode === null ? IDLE_STATE : { status: 'loading', shard: null, error: null };
  });

  const loaderRef = useRef<FacilityShardLoaderHandle | null>(null);
  if (loaderRef.current === null) {
    loaderRef.current = createFacilityShardLoader({ onChange: setState });
  }

  useEffect(() => {
    loaderRef.current?.request(areaCode);
    return () => {
      loaderRef.current?.dispose();
    };
  }, [areaCode]);

  const retry = useCallback(() => {
    loaderRef.current?.retry();
  }, []);

  return { ...state, retry };
}
