import { describe, expect, it } from 'vitest';

import { computeFacilityCoverage, coverageBreakdown } from '../components/FacilityList';
import type { Facility } from '../types';

// 地図に出ていない分の内訳文言。0件の理由を書かないこと（その区域に存在しない
// 理由を「0件」として並べると、実際には起きていない問題を示唆してしまう）を固定する。
describe('coverageBreakdown', () => {
  it('lists only the reasons that actually occur', () => {
    expect(coverageBreakdown({ unmatched: 3, withdrawn: 0 })).toBe('名寄せで位置を特定できず 3件');
    expect(coverageBreakdown({ unmatched: 0, withdrawn: 2 })).toBe('座標が不一致 2件');
  });

  it('joins both reasons when both occur', () => {
    expect(coverageBreakdown({ unmatched: 3, withdrawn: 2 })).toBe('名寄せで位置を特定できず 3件、座標が不一致 2件');
  });

  it('returns an empty string when every facility is on the map', () => {
    expect(coverageBreakdown({ unmatched: 0, withdrawn: 0 })).toBe('');
  });
});

// Inline fixtures only — src/generated/* and public/facilities/* are
// generated by `npm run sync-data`, which does NOT run before `npm run test`
// (see CLAUDE.md「可視化実装で判明した罠」8).

function makeFacility(overrides: Partial<Facility> = {}): Facility {
  return {
    record_id: 'R7-0101-14',
    facility_name: '市立函館病院',
    municipality: '函館市',
    values: [582],
    value_status: ['observed'],
    match_status: 'matched',
    coordinates: [140.7301711, 41.80541985],
    coordinate_source: 'ksj_p04',
    ...overrides,
  };
}

// computeFacilityCoverage: 座標カバレッジの集計。mapped/unmatched/withdrawnに加えて
// M13でreferenceGeocoded（医療情報ネット由来の座標を持つ件数）を数える。
// **座標の有無はcoordinatesの有無で判定する**（match_statusでは判定しない — CLAUDE.md
// 「可視化実装で判明した罠」36）。
describe('computeFacilityCoverage', () => {
  it('counts facilities with coordinates as mapped, split by coordinate_source', () => {
    const p04Facility = makeFacility({ record_id: 'a' });
    const iryojohoFacility = makeFacility({
      record_id: 'b',
      match_status: 'unmatched',
      coordinate_source: 'iryojoho',
    });

    const coverage = computeFacilityCoverage([p04Facility, iryojohoFacility]);

    expect(coverage).toEqual({ mapped: 2, unmatched: 0, withdrawn: 0, referenceGeocoded: 1, total: 2 });
  });

  it('does not count an iryojoho-sourced facility as unmatched even though match_status !== "matched"', () => {
    const facility = makeFacility({ match_status: 'candidate_only', coordinate_source: 'iryojoho' });
    const coverage = computeFacilityCoverage([facility]);
    expect(coverage.mapped).toBe(1);
    expect(coverage.referenceGeocoded).toBe(1);
    expect(coverage.unmatched).toBe(0);
  });

  it('counts a facility without coordinates as unmatched, and one with coordinate_withdrawn as withdrawn', () => {
    const unmatched = makeFacility({ record_id: 'u', match_status: 'unmatched' });
    delete (unmatched as Partial<Facility>).coordinates;
    delete (unmatched as Partial<Facility>).coordinate_source;
    const withdrawn = makeFacility({ record_id: 'w', coordinate_withdrawn: true });
    delete (withdrawn as Partial<Facility>).coordinates;
    delete (withdrawn as Partial<Facility>).coordinate_source;

    const coverage = computeFacilityCoverage([unmatched, withdrawn]);

    expect(coverage).toEqual({ mapped: 0, unmatched: 1, withdrawn: 1, referenceGeocoded: 0, total: 2 });
  });

  it('returns all zeros for null/empty facilities without throwing', () => {
    expect(computeFacilityCoverage(null)).toEqual({ mapped: 0, unmatched: 0, withdrawn: 0, referenceGeocoded: 0, total: 0 });
    expect(computeFacilityCoverage([])).toEqual({ mapped: 0, unmatched: 0, withdrawn: 0, referenceGeocoded: 0, total: 0 });
  });
});
