import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { createFacilityShardLoader, facilityShardUrl, fetchFacilityShard, type FacilityShardState } from './facilityShard';
import type { FacilityShard } from '../types';

// Inline fixtures only — web/src/generated/* and web/public/facilities/* are
// generated by `npm run sync-data`, which does NOT run before `npm run test`
// (vitest has no pre* hook; see CLAUDE.md "可視化実装で判明した罠" #8 and
// facilities.test.ts's identical note). Do not import generated output here.

function makeShard(areaCode: string, overrides: Partial<FacilityShard> = {}): FacilityShard {
  return {
    area_code: areaCode,
    area_name: `エリア${areaCode}`,
    pref_code: areaCode.slice(0, 2),
    pref_name: '県',
    facility_count: 1,
    geocoded_count: 1,
    facilities: [],
    ...overrides,
  };
}

describe('facilityShardUrl', () => {
  it('prefixes the path with import.meta.env.BASE_URL (not a hardcoded absolute path)', () => {
    // A hardcoded "/facilities/..." would 404 once deployed under a GitHub
    // Pages sub-path (vite.config.ts sets base: './') — assert the function
    // actually reads BASE_URL rather than hardcoding.
    expect(facilityShardUrl('0101')).toBe(`${import.meta.env.BASE_URL}facilities/0101.json`);
    expect(facilityShardUrl('4001')).toBe(`${import.meta.env.BASE_URL}facilities/4001.json`);
  });
});

describe('fetchFacilityShard', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('throws (including the HTTP status) when the response is not ok', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({ ok: false, status: 404, json: async () => ({}) })
    );
    await expect(fetchFacilityShard('0101')).rejects.toThrow(/404/);
  });

  it('throws when the response area_code does not match the requested one', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => makeShard('0102') })
    );
    await expect(fetchFacilityShard('0101')).rejects.toThrow(/0101/);
  });

  it('resolves the shard when the response is ok and area_code matches', async () => {
    const shard = makeShard('0101');
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => shard }));
    await expect(fetchFacilityShard('0101')).resolves.toEqual(shard);
  });

  it('passes the AbortSignal through to fetch', async () => {
    const fetchMock = vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => makeShard('0101') });
    vi.stubGlobal('fetch', fetchMock);
    const controller = new AbortController();
    await fetchFacilityShard('0101', { signal: controller.signal });
    expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('0101.json'), { signal: controller.signal });
  });
});

// ---- createFacilityShardLoader: race-condition handling -------------------
//
// The brief calls out (codex's review point): switching areas quickly must
// never let a late-arriving response for the *previous* area overwrite the
// state of the *newly* selected area. This is exercised directly against the
// loader (not the useFacilityShard hook) because this repo's vitest has no
// jsdom/@testing-library/react dependency — see the module comment in
// facilityShard.ts.

function deferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (err: unknown) => void;
  const promise = new Promise<T>((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}

describe('createFacilityShardLoader', () => {
  let cache: Map<string, FacilityShard>;
  let states: FacilityShardState[];

  beforeEach(() => {
    cache = new Map();
    states = [];
  });

  it('does not let a stale (superseded) area response overwrite the newer selection, even if it resolves later', async () => {
    const shardA = makeShard('0101');
    const shardB = makeShard('4001');
    const pendingA = deferred<FacilityShard>();
    const pendingB = deferred<FacilityShard>();

    const fetcher = vi.fn((areaCode: string) => {
      if (areaCode === '0101') return pendingA.promise;
      if (areaCode === '4001') return pendingB.promise;
      throw new Error(`unexpected areaCode ${areaCode}`);
    });

    const loader = createFacilityShardLoader({ cache, fetcher, onChange: (s) => states.push(s) });

    loader.request('0101'); // A: loading
    loader.request('4001'); // user quickly switches to B before A resolves; supersedes A

    // B resolves first (plausible: A might be a large/slow shard, B small).
    pendingB.resolve(shardB);
    await pendingB.promise;
    await Promise.resolve();

    // A resolves late, *after* B has already been adopted.
    pendingA.resolve(shardA);
    await pendingA.promise;
    await Promise.resolve();

    const last = states[states.length - 1];
    expect(last.status).toBe('loaded');
    expect(last.shard?.area_code).toBe('4001');
    // A's late resolution must never have produced a state pointing at 0101.
    expect(states.some((s) => s.shard?.area_code === '0101')).toBe(false);
    // ...and must not have poisoned the cache with a stale entry either.
    expect(cache.has('0101')).toBe(false);
    expect(cache.get('4001')).toEqual(shardB);
  });

  it('does not surface a stale area rejection (e.g. a 404 for the previous area) as an error for the current selection', async () => {
    const shardB = makeShard('4001');
    const pendingA = deferred<FacilityShard>();
    const pendingB = deferred<FacilityShard>();
    const fetcher = vi.fn((areaCode: string) => (areaCode === '0101' ? pendingA.promise : pendingB.promise));

    const loader = createFacilityShardLoader({ cache, fetcher, onChange: (s) => states.push(s) });

    loader.request('0101');
    loader.request('4001');

    pendingB.resolve(shardB);
    await pendingB.promise;
    await Promise.resolve();

    pendingA.reject(new Error('HTTP 404'));
    // Let the rejection's microtask settle without an unhandled-rejection failure.
    await pendingA.promise.catch(() => undefined);
    await Promise.resolve();

    const last = states[states.length - 1];
    expect(last.status).toBe('loaded');
    expect(last.shard?.area_code).toBe('4001');
  });

  it('serves a cached shard synchronously (no loading state, no fetch) on reselect', () => {
    const shard = makeShard('0101');
    cache.set('0101', shard);
    const fetcher = vi.fn();

    const loader = createFacilityShardLoader({ cache, fetcher, onChange: (s) => states.push(s) });
    loader.request('0101');

    expect(fetcher).not.toHaveBeenCalled();
    expect(states).toEqual([{ status: 'loaded', shard, error: null }]);
  });

  it('goes idle when areaCode is null', () => {
    const fetcher = vi.fn();
    const loader = createFacilityShardLoader({ cache, fetcher, onChange: (s) => states.push(s) });
    loader.request(null);
    expect(fetcher).not.toHaveBeenCalled();
    expect(states).toEqual([{ status: 'idle', shard: null, error: null }]);
  });

  it('retry() bypasses the cache and re-issues the request for the current area', async () => {
    const shard = makeShard('0101');
    const fetcher = vi.fn().mockResolvedValue(shard);
    const loader = createFacilityShardLoader({ cache, fetcher, onChange: (s) => states.push(s) });

    loader.request('0101');
    await Promise.resolve();
    await Promise.resolve();
    expect(states[states.length - 1]).toEqual({ status: 'loaded', shard, error: null });

    fetcher.mockClear();
    cache.clear(); // simulate: nothing to serve from cache (e.g. a prior failed attempt)
    loader.retry();
    expect(fetcher).toHaveBeenCalledTimes(1);
    expect(fetcher).toHaveBeenCalledWith('0101', expect.anything());
  });

  it('retry() is a no-op when no area has ever been requested', () => {
    const fetcher = vi.fn();
    const loader = createFacilityShardLoader({ cache, fetcher, onChange: (s) => states.push(s) });
    loader.retry();
    expect(fetcher).not.toHaveBeenCalled();
    expect(states).toEqual([]);
  });
});
