// Fetching/caching of the patient-flow dataset (web/public/flow/area_flow.json).
// Splits the same way facilityShard.ts does:
//   - pure/side-effect-light helpers (flowDataUrl, fetchFlowData, loadFlowData)
//     that vitest can exercise directly with a mocked fetch — no DOM/React
//     rendering required (this repo's vitest has no jsdom/testing-library
//     dependency, see flowData.test.ts)
//   - the React hook (useFlowData) that is a thin wrapper around loadFlowData,
//     wiring it to useState/useEffect
//
// Unlike facilityShard.ts, there is no per-area state machine here: the whole
// dataset is a single ~499KB (gzip ~126KB) file, fetched at most once and
// reused for every area — see web/scripts/sync-data.mjs's "5b." write step
// for why it is not split per area like the facility shards.
//
// See CLAUDE.md "可視化実装で判明した罠" 8: web/src/generated/* and
// web/public/flow/* are generated by `npm run sync-data`, which does NOT run
// before `npm run test` — this file and its test must not import them.

import { useCallback, useEffect, useState } from 'react';
import type { AreaFlowData } from '../types';

/**
 * URL of the patient-flow dataset. Must be built from import.meta.env.BASE_URL
 * (vite.config.ts sets `base: './'`) rather than an absolute `/flow/...` path
 * — an absolute path 404s once the site is deployed under a GitHub Pages
 * sub-path (see facilityShard.ts's facilityShardUrl for the identical trap).
 */
export function flowDataUrl(): string {
  return `${import.meta.env.BASE_URL}flow/area_flow.json`;
}

export interface FetchFlowDataOptions {
  signal?: AbortSignal;
}

/**
 * Fetches and minimally validates the patient-flow dataset. Throws (rather
 * than returning a Result type, matching fetchFacilityShard's convention) on
 * a non-2xx response or a payload whose `areas` is not an array — the latter
 * catches a truncated/malformed file without requiring a full schema check
 * here (web/scripts/sync-data.mjs already validates the source thoroughly
 * before writing this file).
 */
export async function fetchFlowData(options: FetchFlowDataOptions = {}): Promise<AreaFlowData> {
  const res = await fetch(flowDataUrl(), { signal: options.signal });
  if (!res.ok) {
    throw new Error(`患者の流入出データの取得に失敗しました: HTTP ${res.status}`);
  }
  const data = (await res.json()) as AreaFlowData;
  if (!data || !Array.isArray(data.areas)) {
    throw new Error('患者の流入出データの形式が不正です（areasが配列ではありません）');
  }
  return data;
}

// モジュールスコープのPromiseキャッシュ。呼び出しが何回来ても取得は高々1回
// （区域を切り替えるたびに取得先が変わる医療機関shardと違い、データセットは
// 全体で1本しかないため — flowData.tsの冒頭コメント参照）。失敗したPromiseは
// キャッシュに残さない(nullに戻す)ことで、次のloadFlowData()呼び出しが必ず
// 再取得しに行くようにする(でなければretry()が永久に同じ失敗を返し続ける)。
let flowDataPromise: Promise<AreaFlowData> | null = null;

export function loadFlowData(): Promise<AreaFlowData> {
  if (flowDataPromise === null) {
    flowDataPromise = fetchFlowData().catch((err: unknown) => {
      flowDataPromise = null;
      throw err;
    });
  }
  return flowDataPromise;
}

/** テスト専用: モジュールスコープのPromiseキャッシュをリセットする。 */
export function _resetFlowDataCacheForTests(): void {
  flowDataPromise = null;
}

export type FlowDataStatus = 'idle' | 'loading' | 'loaded' | 'error';

export interface UseFlowDataResult {
  status: FlowDataStatus;
  data: AreaFlowData | null;
  error: string | null;
  /** 失敗後の再試行。loadFlowData()は失敗したPromiseをキャッシュしないため、
   * 呼び直すだけで再取得が走る。 */
  retry: () => void;
}

/**
 * `enabled` が真になって初めて `loadFlowData()` を呼ぶフック
 * （区域が一度も選ばれていない間は取得しない）。
 *
 * アンマウント後にsetStateしない・React 18 StrictModeの二重実行でも壊れない
 * のは、useFacilityShard(facilityShard.ts)と同じ理由で、Reactのライフサイクル
 * に依存する真偽値フラグ(isMounted的なref)ではなく、各effect実行に閉じた
 * `cancelled` ローカル変数で判定しているため: StrictModeがeffectを
 * 実行→クリーンアップ→再実行しても、クリーンアップ済みの実行のクロージャの
 * `cancelled` だけがtrueになり、新しい実行の状態更新を妨げない。
 */
export function useFlowData(enabled: boolean): UseFlowDataResult {
  const [status, setStatus] = useState<FlowDataStatus>('idle');
  const [data, setData] = useState<AreaFlowData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [retryToken, setRetryToken] = useState(0);

  useEffect(() => {
    if (!enabled) return undefined;

    let cancelled = false;
    setStatus((prev) => (prev === 'loaded' ? prev : 'loading'));
    setError(null);

    loadFlowData()
      .then((result) => {
        if (cancelled) return;
        setData(result);
        setStatus('loaded');
        setError(null);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setStatus('error');
        setError(err instanceof Error ? err.message : String(err));
      });

    return () => {
      cancelled = true;
    };
  }, [enabled, retryToken]);

  const retry = useCallback(() => {
    setRetryToken((t) => t + 1);
  }, []);

  return { status, data, error, retry };
}
