import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { _resetFlowDataCacheForTests, fetchFlowData, flowDataUrl, loadFlowData } from './flowData';
import type { AreaFlowData } from '../types';

// Inline fixtures only — web/src/generated/* and web/public/flow/* are
// generated by `npm run sync-data`, which does NOT run before `npm run test`
// (vitest has no pre* hook; see CLAUDE.md "可視化実装で判明した罠" #8 and
// facilityShard.test.ts's identical note). Do not import generated output here.

function makeFlowData(overrides: Partial<AreaFlowData> = {}): AreaFlowData {
  return {
    metadata: {
      title: 'テスト用タイトル',
      source: {
        name: 'テスト用出典',
        publisher: '厚生労働省',
        url: 'https://example.invalid/001723366.xlsx',
        page_url: 'https://example.invalid/',
        fiscal_year: '令和7年度（2025年度）',
        source_file: 'R7/001723366.xlsx',
        source_sha256: 'x'.repeat(64),
        source_sheet: ['流入率', '流出率'],
        acquired_date: '2026-08-04',
        license: 'テスト用ライセンス',
        original_title: '流入率・流出率',
        original_notes: [],
        derived_via: [],
      },
      processing: {
        script: 'tools/build_web_flow.py',
        inputs: [],
        steps: [],
        caveat: { patient_flow: 'テスト用caveat1', patient_flow_total: 'テスト用caveat2' },
      },
      fields: {},
      known_issues: [],
    },
    directions: ['inflow', 'outflow'],
    direction_labels: { inflow: '流入率', outflow: '流出率' },
    phases: ['acute', 'comprehensive', 'chronic'],
    phase_labels: { acute: '高度急性期+急性期', comprehensive: '包括期', chronic: '慢性期' },
    areas: [],
    ...overrides,
  };
}

describe('flowDataUrl', () => {
  it('prefixes the path with import.meta.env.BASE_URL (not a hardcoded absolute path)', () => {
    // A hardcoded "/flow/..." would 404 once deployed under a GitHub Pages
    // sub-path (vite.config.ts sets base: './') — assert the function
    // actually reads BASE_URL rather than hardcoding.
    expect(flowDataUrl()).toBe(`${import.meta.env.BASE_URL}flow/area_flow.json`);
  });
});

describe('fetchFlowData', () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('throws (including the HTTP status) when the response is not ok', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({ ok: false, status: 500, json: async () => ({}) })
    );
    await expect(fetchFlowData()).rejects.toThrow(/500/);
  });

  it('throws a meaningful message when the payload is malformed (areas is not an array)', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => ({ areas: 'not-an-array' }) })
    );
    await expect(fetchFlowData()).rejects.toThrow(/areas/);
  });

  it('resolves the data when the response is ok and areas is an array', async () => {
    const flow = makeFlowData();
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => flow }));
    await expect(fetchFlowData()).resolves.toEqual(flow);
  });

  it('passes the AbortSignal through to fetch', async () => {
    const fetchMock = vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => makeFlowData() });
    vi.stubGlobal('fetch', fetchMock);
    const controller = new AbortController();
    await fetchFlowData({ signal: controller.signal });
    expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('flow/area_flow.json'), {
      signal: controller.signal,
    });
  });
});

// ---- loadFlowData: module-scope Promise cache ------------------------------

describe('loadFlowData', () => {
  beforeEach(() => {
    _resetFlowDataCacheForTests();
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    _resetFlowDataCacheForTests();
  });

  it('fetches at most once across repeated calls (module-scope cache)', async () => {
    const flow = makeFlowData();
    const fetchMock = vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => flow });
    vi.stubGlobal('fetch', fetchMock);

    const first = loadFlowData();
    const second = loadFlowData();

    await expect(first).resolves.toEqual(flow);
    await expect(second).resolves.toEqual(flow);
    expect(fetchMock).toHaveBeenCalledTimes(1);
    // Both calls return the very same Promise instance, not just equal data.
    expect(first).toBe(second);
  });

  it('does not cache a failed attempt: a later call re-issues the fetch', async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: false, status: 503, json: async () => ({}) })
      .mockResolvedValueOnce({ ok: true, status: 200, json: async () => makeFlowData() });
    vi.stubGlobal('fetch', fetchMock);

    await expect(loadFlowData()).rejects.toThrow(/503/);
    expect(fetchMock).toHaveBeenCalledTimes(1);

    // retry() in the hook is just "call loadFlowData() again" — exercise
    // that directly here since the hook itself needs a DOM to render.
    await expect(loadFlowData()).resolves.toEqual(makeFlowData());
    expect(fetchMock).toHaveBeenCalledTimes(2);
  });
});
